[WAGON-592] Wagon fails when compiled on Java 9+ and run on Java 8 due to JDK API breakage
Cast to Buffer to avoid java.lang.NoSuchMethodError.
See https://github.com/mongodb/mongo-java-driver/commit/21c91bd364d38489e0bbe2e390efdb3746ee3fff
for details.